"""migration update timezone at inv

Revision ID: 01aa2914cdd6
Revises: 7f18034d9781
Create Date: 2025-03-20 02:38:24.203572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01aa2914cdd6'
down_revision: Union[str, None] = '7f18034d9781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
