"""Add unique constraint to company name

Revision ID: 3bd852aa8991
Revises: d91dbd38d1a8
Create Date: 2025-03-15 09:59:49.017568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bd852aa8991"
down_revision: Union[str, None] = "d91dbd38d1a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "companies", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "companies", type_="unique")
    # ### end Alembic commands ###
