"""migration update timezone at inv

Revision ID: 501dcdd5bf1c
Revises: 01aa2914cdd6
Create Date: 2025-03-20 03:27:52.188765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501dcdd5bf1c'
down_revision: Union[str, None] = '01aa2914cdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
