"""Allow age to be null

Revision ID: 99ec647c62ef
Revises: ad1ce4c8a042
Create Date: 2025-03-07 10:13:18.348411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99ec647c62ef"
down_revision: Union[str, None] = "ad1ce4c8a042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
