"""migration 9

Revision ID: aec949182c4d
Revises: 2bd723a87540
Create Date: 2025-03-24 05:55:08.387319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec949182c4d'
down_revision: Union[str, None] = '2bd723a87540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_membership_requests_company_id_fkey', 'company_membership_requests', type_='foreignkey')
    op.create_foreign_key(None, 'company_membership_requests', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_membership_requests', type_='foreignkey')
    op.create_foreign_key('company_membership_requests_company_id_fkey', 'company_membership_requests', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
